name: Sync README to Miraheze Wiki

on:
  push:
    paths:
      - README.md    # Trigger this workflow when README.md changes
  workflow_dispatch:  # Allows you to manually trigger this workflow

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Sync README.md to Miraheze Wiki
        run: |
          # Extract the content of README.md
          README_CONTENT=$(cat README.md)

          # Use the Miraheze API to update the wiki page (Main_Page in this example)
          curl -X POST \
            -d "action=edit&title=Main_Page&text=$README_CONTENT&bot=1" \
            -d "format=json" \
            -d "username=${{ secrets.MIRAHEZE_USERNAME }}" \
            -d "password=${{ secrets.MIRAHEZE_PASSWORD }}" \
            ${{ secrets.MIRAHEZE_WIKI_URL }}
