name: Sync README to Miraheze Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: sudo apt-get install -y curl jq

      - name: Login to Miraheze
        env:
          BOT_PASSWORD: ${{ secrets.MIRAHEZE_BOT_PASSWORD }}
        run: |
          # Step 1: Get login token
          LOGIN_RESPONSE=$(curl -sS \
            -d "action=login" \
            -d "lgname=Alexisyoj23@Mikafleur123" \
            -d "lgpassword=$BOT_PASSWORD" \
            -d "format=json" \
            https://panalawahigdocs.miraheze.org/w/api.php)
          LOGIN_TOKEN=$(echo "$LOGIN_RESPONSE" | jq -r '.login.token')

          # Step 2: Complete login
          curl -sS \
            -d "action=login" \
            -d "lgname=Alexisyoj23@Mikafleur123" \
            -d "lgpassword=$BOT_PASSWORD" \
            -d "lgtoken=$LOGIN_TOKEN" \
            -d "format=json" \
            https://panalawahigdocs.miraheze.org/w/api.php

      - name: Get Edit Token
        run: |
          EDIT_TOKEN=$(curl -sS \
            "https://panalawahigdocs.miraheze.org/w/api.php?action=query&meta=tokens&format=json" \
            | jq -r '.query.tokens.csrftoken')
          echo "EDIT_TOKEN=$EDIT_TOKEN" >> $GITHUB_ENV

      - name: Update Wiki Page
        run: |
          # Encode content and update page
          curl -X POST \
            -H "Content-Type: application/x-www-form-urlencoded" \
            --data-urlencode "title=Main Page" \
            --data-urlencode "text=$(cat README.md)" \
            --data-urlencode "token=$EDIT_TOKEN" \
            --data-urlencode "format=json" \
            "https://panalawahigdocs.miraheze.org/w/api.php?action=edit"
